variables:
  PRIMARY_BRANCH: "main"
  DEPLOY_REPO: 'git@gitlab.clarium.tech:clarium-org-apps/workforce/workforce-apps-deploy.git'
  TARGET_BRANCH: "stage-dev"
  MODULE: "employee-information-api"
  DLL_NAME: "EmpInfoInner.dll"
  PROJECT_FILE: "EmployeeInformationInner.sln"
   
include:
  - project: "devops/gitlab_yamls"
    ref: "Framework_template"
    file: "dotnet.gitlab-ci.yml"
